name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Archive Release
        run: zip gal_KR-commuter.zip *.pak compat_archive\${{ github.ref_name }}\compat.tab
        
      - name: Edit ReleaseNote
        run: sed -i '1i**ダウンロードはページ下部にあります**\n' ReadMe.Md
        
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gal_KR-commuter.zip"
          bodyFile: "ReadMe.Md"
          token: ${{ secrets.GITHUB_TOKEN }}